services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__PrivateKey: $${{ secrets.JWT_PRIVATE_KEY }}
      Jwt__PublicKey: $${{ secrets.JWT_PUBLIC_KEY }}
      Jwt__Issuer: $${{ secrets.JWT_ISSUER }}
      Jwt__Audience: $${{ secrets.JWT_AUDIENCE }}
    ports:
      - "8000:8000"
