services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt_PrivateKey: ${JWT__PRIVATE_KEY}
      Jwt_PublicKey: ${JWT__PUBLIC_KEY}
      Jwt_Issuer: ${JWT__ISSUER}
      Jwt_Audience: ${JWT__AUDIENCE}
    ports:
      - "8000:8000"
