services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt_PrivateKey: ${JWT_PRIVATE_KEY}
      Jwt_PublicKey: ${JWT_PUBLIC_KEY}
      Jwt_Issuer: ${JWT_ISSUER}
      Jwt_Audience: ${JWT_AUDIENCE}
    ports:
      - "8000:8000"
