services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__PrivateKey: ${JWT_PRIVATE_KEY}
      Jwt__PublicKey: ${JWT_PUBLIC_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
    ports:
      - "8000:8000"