services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt_PrivateKey: ${{ sercrets.JWT__PRIVATE_KEY }}
      Jwt_PublicKey: ${{ secrets.JWT__PUBLIC_KEY }}
      Jwt_Issuer: ${{ secrets.JWT__ISSUER }}
      Jwt_Audience: ${{ secrets.JWT__AUDIENCE }}
    ports:
      - "8000:8000"
